### ISSUE TITLE
电子书不管用git还是用IDM都下不了，怎么回事

### ISSUE THREAD

**Issue by Tracker647** [biaochenxuying/awesome-books#2]
之前试着用IDM，结果下下来的就是1G不到的压缩文件，书全都看不了；
再试着用原生的下载方式，但是Chrome没下多久就显示网络错误。

**Comment by biaochenxuying** [comment]
![](https://user-images.githubusercontent.com/24362914/99151270-e0b7db80-26d4-11eb-8f2c-64fa52800087.png)

可以下载的啊，应该是你的网络问题。
如果实在不行，可以关注公众号：全栈修炼，回复 电子书 即可获得全部的电子书的下载链接。
